version: '3.3'

services:
  postgres:
    image: postgres:15
    container_name: postgres_app
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env_non_dev


  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env_non_dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env_non_dev
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env_non_dev
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
