version: '3.3'

services:
  postgres:
    image: postgres:latest
    privileged: true
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - '5432:5432'
    env_file:
      - '.env'
    volumes:
      - ./pg_data:/var/lib/postgresql/data