# Докер для разработки
version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: pg_database
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"